### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by wfs233** [NUSTM/FMNERG#1]
This problem occurs when I run the run.sh file.
 
 
 ============================== NEW EXP: ASQP on Twitter10000V2.0 ==============================

Here is an example (from the dev set):
Total examples = 1501
Traceback (most recent call last):
  File "/root/autodl-tmp/FMNERG/data_utils.py", line 121, in turn_labels_to_quad_and_get_visual_features
    img = np.load(os.path.join(img_path_vinvl, str(img_id) + '.npz'))
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 420, in load
    ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 187, in __init__
    _zip = zipfile_factory(fid)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/root/miniconda3/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 411, in <module>
    dataset = get_dataset(tokenizer=tokenizer, data_type='dev', args=args)
  File "main.py", line 119, in get_dataset
    return VisualDataset(
  File "/root/autodl-tmp/FMNERG/data_utils.py", line 333, in __init__
    self._build_examples()
  File "/root/autodl-tmp/FMNERG/data_utils.py", line 359, in _build_examples
    = get_transformed_io(
  File "/root/autodl-tmp/FMNERG/data_utils.py", line 289, in get_transformed_io
    read_line_examples_from_file(
  File "/root/autodl-tmp/FMNERG/data_utils.py", line 230, in read_line_examples_from_file
    turn_labels_to_quad_and_get_visual_features(
  File "/root/autodl-tmp/FMNERG/data_utils.py", line 123, in turn_labels_to_quad_and_get_visual_features
    img = np.load('/root/data2/twitter_images/twitter2015_vinvl_extract36/0.jpg.npz')
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/root/data2/twitter_images/twitter2015_vinvl_extract36/0.jpg.npz'

**Comment by zyLiRere** [comment]
Apologies for the inconvenience caused by the absolute path in the code. We've rectified this by revising the code to use relative paths and have added the '0.jpg.npz' file to the twitterFMNERG_vinvl_extract36 folder.
