### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'head_mask'

### ISSUE THREAD

**Issue by Wang-Zhenxing** [NUSTM/FMNERG#7]
**Have you encountered this problem during the process of configuring the operating environment?**

**Could you please give us more information about your environment configuration?**

**Thank you!**

> My machine cannot run according to the operating environment configured in requirement.txt, so my configuration is as follows. Here is my main environment configuration：

```
python                    3.8.19               h955ad1f_0
pytorch-lightning         0.8.1                    pypi_0    pypi
torch                     1.8.0+cu111              pypi_0    pypi
torchaudio                0.8.0                    pypi_0    pypi
torchvision               0.9.0+cu111              pypi_0    pypi
transformers              4.18.0                   pypi_0    pypi
```

```
NVIDIA GeForce RTX 3070 GPU
CUDA version 11.3
```

> **The Error：**

```
Traceback (most recent call last):
  File "main.py", line 462, in <module>
    trainer.fit(model)
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in fit
    self.single_gpu_train(model)
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 176, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1073, in run_pretrain_routine
    eval_results = self._evaluate(model,
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 281, in _evaluate
    output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 452, in evaluation_forward
    output = model.validation_step(*args)
  File "main.py", line 204, in validation_step
    loss = self._step(batch)
  File "main.py", line 171, in _step
    outputs = self(
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "main.py", line 150, in forward
    return self.model(
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/itechs/data/wangzhenxing/code/FMNERG/VisionT5.py", line 429, in forward
    encoder_outputs = self.encoder(
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/itechs/data/wangzhenxing/code/FMNERG/VisionT5.py", line 264, in forward
    layer_outputs = layer_module(
  File "/home/itechs/data/anaconda3/envs/fmnerg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'head_mask'
```

**Comment by Wang-Zhenxing** [comment]
**I have solved this problem! This code can be run! Excuse me!**

> **Replace these package：**

```
torch                     1.7.0+cu110
torchaudio                0.7.0
torchvision               0.8.1+cu110
transformers              4.0.0
```
